version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip3 install poetry
            python3 -m venv venv
            . venv/bin/activate
            poetry install
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --statistics
            pylint src tests
            bandit
            mypy
            pytest -v --cov
